apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv.maven
  namespace: jenkins
  labels:
    name: maven
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/maven/repository"
