apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc.maven
  namespace: jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
