Master:
  # FIXME: for easier testing set the password to abcd1234.
  AdminPassword: abcd1234
  ServiceType: NodePort
  InstallPlugins:
    - kubernetes:1.3.2
    - workflow-aggregator:2.5
    - workflow-job:2.17
    - credentials-binding:1.15
    - git:3.8.0
    #- ghprb:1.40.0
    #- blueocean:1.4.2
